# Generated by Django 3.1.7 on 2021-03-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20210307_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='الخبرة',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='المرتب',
            new_name='salary',
        ),
    ]
