# Generated by Django 3.1.7 on 2021-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20210307_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('4 Hours ', '4 Hours'), ('40 Hours ', '40 Hours'), ('420 Hours ', '420 Hours')], max_length=100),
        ),
    ]
